admVarAtemluftInLiter = 1800;	
admVarFlaschenVolumen = 6;
admVarFlaschendruckInBar = 300;
admVarProzentSauerstoff = 0.15;
admVarProzentStickstoff = 0.30;
admVarProzentHelium = 0.55;
admVarTaucherOhneLuft = 0;
player removeItem "adm_item_cylinder_1btl_6ltr_300bar_Tx1555";
playSound "adm_sound_zischen";
hint "Filled rebreather using one single 6l bottle, filled with 300bar of Tx15/55.";
player addItem "adm_item_cylinder_1btl_6ltr_empty";